name: Unit Tests & Build

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    name: Build, Vet and Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Tidy and verify dependencies
      run: go mod tidy && go mod verify

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Unit tests
      run: go test -v $(go list ./... | grep -v ministry-mapper/internal/setup)